Make cross compiling a real possibility, with instructions.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3,6 +3,88 @@
 # This configure script written by Brian Callahan <bcallah@openbsd.org>
 # and released into the Public Domain.
 
+Makefile() {
+  if [ -z "$cc" ] ; then
+    cc=$CC
+  fi
+cat << EOF > Makefile
+# This Makefile automatically generated by configure.
+
+CC =		$cc
+CFLAGS =	$cflags -std=gnu99
+EOF
+
+if [ ! -z "$ldflags" ] ; then
+cat << EOF >> Makefile
+LDFLAGS =	$ldflags
+EOF
+fi
+
+cat << EOF >> Makefile
+
+PREFIX =	$prefix
+BINDIR =	$bindir
+MANDIR =	$mandir
+
+PROG =	$instprog
+OBJS =	alloc.o asprintf.o c_ksh.o c_sh.o c_test.o c_ulimit.o edit.o \\
+	emacs.o eval.o exec.o expr.o history.o io.o jobs.o lex.o mail.o \\
+	main.o misc.o path.o shf.o syn.o table.o trap.o tree.o tty.o var.o \\
+	version.o vi.o confstr.o reallocarray.o siglist.o signame.o \\
+	strlcat.o strlcpy.o strtonum.o unvis.o vis.o
+
+all: \${PROG}
+
+\${PROG}: \${OBJS}
+EOF
+
+if [ $compileonly -eq 0 ] ; then
+cat << EOF >> Makefile
+	\${CC} \${LDFLAGS} -o \${PROG} \${OBJS} $libs
+EOF
+fi
+
+cat << EOF >> Makefile
+
+install:
+	install -d \${DESTDIR}\${BINDIR}
+	install -d \${DESTDIR}\${MANDIR}/man1
+	install -c -s -m 755 \${PROG} \${DESTDIR}\${BINDIR}
+	install -c -m 644 oksh.1 \${DESTDIR}\${MANDIR}/man1/\${PROG}.1
+EOF
+
+if [ $instsh -ne 0 ] ; then
+cat << EOF >> Makefile
+	install -d \${DESTDIR}\${BINDIR}
+	install -d \${DESTDIR}\${MANDIR}/man1
+	install -c -s -m 755 \${PROG} \${DESTDIR}\${BINDIR}/sh
+	install -c -m 644 sh.1 \${DESTDIR}\${MANDIR}/man1
+EOF
+fi
+
+cat << EOF >> Makefile
+	@echo "Please add $bindir/$instprog to /etc/shells"
+EOF
+
+if [ $instsh -ne 0 ] ; then
+cat << EOF >> Makefile
+	@echo "Please add $bindir/sh to /etc/shells"
+EOF
+fi
+
+cat << EOF >> Makefile
+
+test:
+	echo "No tests"
+
+clean:
+	rm -f \${PROG} \${OBJS}
+
+distclean: clean
+	rm -f Makefile pconfig.h
+EOF
+}
+
 asprintfcheck() {
   cat << EOF > conftest.c
 #include <stdio.h>
@@ -237,7 +319,7 @@ EOF
 noreturncheck() {
   cat << EOF > conftest.c
 #include <stdlib.h>
-__attribute__((noreturn)) usage(void){exit(1);}int main(void){usage();return 0;}
+__attribute__((__noreturn__)) usage(void){exit(1);}int main(void){usage();return 0;}
 EOF
   $cc $cflags $ldflags -o conftest conftest.c > /dev/null 2>&1
   if [ $? -eq 0 ] ; then
@@ -534,6 +616,8 @@ else
   prefix="/usr/local"
 fi
 
+doconfigure=1
+compileonly=0
 bindirset=0
 mandirset=0
 bindir="$prefix/bin"
@@ -602,6 +686,12 @@ do
 	  lto=0
 	fi
 	;;
+    --no-thanks)
+	doconfigure=0
+	;;
+    --no-link)
+	compileonly=1
+	;;
     --help|-h)
 	echo "Usage: configure [options]"
 	echo ""
@@ -624,6 +714,10 @@ do
 	echo "Install additional sh executable [default=no]"
 	printf "  --enable-static         "
 	echo "Statically link executables [default=no]"
+	printf "  --no-thanks             "
+	echo "Skip all configure checks"
+	printf "  --no-link               "
+	echo "Compile only, do not link (requires --no-thanks)"
 	exit 1
 	;;
     *)
@@ -645,6 +739,53 @@ fi
 
 if [ $static -ne 0 ] ; then
   ldflags="${ldflags}-static"
+fi
+
+if [ $compileonly -eq 1 ] ; then
+  if [ $doconfigure -eq 1 ] ; then
+    echo "ERROR: --no-link requires --no-thanks"
+    exit 1
+  fi
+fi
+
+if [ $doconfigure -eq 0 ] ; then
+  echo "OK, I trust you."
+  echo "I'll assume you have gcc/clang and little else."
+  echo "Edit Makefile and pconfig.h if needed."
+  echo "Good luck!"
+  cat << EOF > pconfig.h
+/* This file automatically generated by configure.  */
+
+#ifndef __dead
+#define __dead __attribute__((__noreturn__))
+#endif
+
+/* #define __attribute__(x) */
+
+/* #define HAVE_ASPRINTF */
+/* #define HAVE_CONFSTR */
+#define NO_CURSES
+/* #define HAVE_PLEDGE */
+/* #define HAVE_REALLOCARRAY */
+/* #define HAVE_SETRESGID */
+/* #define HAVE_SETRESUID */
+/* #define HAVE_SIG_T */
+/* #define HAVE_SRAND_DETERMINISTIC */
+/* #define HAVE_ST_MTIM */
+#define HAVE_ST_MTIMESPEC
+/* #define HAVE_STRAVIS */
+/* #define HAVE_STRLCAT */
+/* #define HAVE_STRLCPY */
+/* #define HAVE_STRTONUM */
+/* #define HAVE_STRUNVIS */
+/* #define HAVE_SIGLIST */
+/* #define HAVE_SIGNAME */
+/* #define HAVE_TIMERADD */
+/* #define HAVE_TIMERSUB */
+EOF
+  Makefile
+
+  exit 0
 fi
 
 printf "checking for C compiler... "
@@ -977,72 +1118,5 @@ else
 fi
 
 printf "creating Makefile... "
-cat << EOF > Makefile
-# This Makefile automatically generated by configure.
-
-CC =		$cc
-CFLAGS =	$cflags
-EOF
-
-if [ ! -z "$ldflags" ] ; then
-cat << EOF >> Makefile
-LDFLAGS =	$ldflags
-EOF
-fi
-
-cat << EOF >> Makefile
-
-PREFIX =	$prefix
-BINDIR =	$bindir
-MANDIR =	$mandir
-
-PROG =	$instprog
-OBJS =	alloc.o asprintf.o c_ksh.o c_sh.o c_test.o c_ulimit.o edit.o \\
-	emacs.o eval.o exec.o expr.o history.o io.o jobs.o lex.o mail.o \\
-	main.o misc.o path.o shf.o syn.o table.o trap.o tree.o tty.o var.o \\
-	version.o vi.o confstr.o reallocarray.o siglist.o signame.o \\
-	strlcat.o strlcpy.o strtonum.o unvis.o vis.o
-
-all: \${PROG}
-
-\${PROG}: \${OBJS}
-	\${CC} \${LDFLAGS} -o \${PROG} \${OBJS} $libs
-
-install:
-	install -d \${DESTDIR}\${BINDIR}
-	install -d \${DESTDIR}\${MANDIR}/man1
-	install -c -s -m 755 \${PROG} \${DESTDIR}\${BINDIR}
-	install -c -m 644 oksh.1 \${DESTDIR}\${MANDIR}/man1/\${PROG}.1
-EOF
-
-if [ $instsh -ne 0 ] ; then
-cat << EOF >> Makefile
-	install -d \${DESTDIR}\${BINDIR}
-	install -d \${DESTDIR}\${MANDIR}/man1
-	install -c -s -m 755 \${PROG} \${DESTDIR}\${BINDIR}/sh
-	install -c -m 644 sh.1 \${DESTDIR}\${MANDIR}/man1
-EOF
-fi
-
-cat << EOF >> Makefile
-	@echo "Please add $bindir/$instprog to /etc/shells"
-EOF
-
-if [ $instsh -ne 0 ] ; then
-cat << EOF >> Makefile
-	@echo "Please add $bindir/sh to /etc/shells"
-EOF
-fi
-
-cat << EOF >> Makefile
-
-test:
-	echo "No tests"
-
-clean:
-	rm -f \${PROG} \${OBJS}
-
-distclean: clean
-	rm -f Makefile pconfig.h
-EOF
+Makefile
 echo "done"
